SELECT D3.ID
FROM ECOLI_DATA D1 
LEFT OUTER JOIN ECOLI_DATA D2 ON D1.ID = D2.PARENT_ID
LEFT OUTER JOIN ECOLI_DATA D3 ON D2.ID = D3.PARENT_ID
WHERE D1.PARENT_ID IS NULL AND D3.PARENT_ID IS NOT NULL
ORDER BY D3.ID;