SELECT t1.FOOD_TYPE, REST_ID, REST_NAME, t1.FAVORITES
FROM(
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO 
    GROUP BY FOOD_TYPE
) AS t1
JOIN REST_INFO t2 ON t1.FOOD_TYPE = t2.FOOD_TYPE AND t1.FAVORITES = t2.FAVORITES
ORDER BY FOOD_TYPE DESC