# SELECT i.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
# FROM REST_INFO i JOIN REST_REVIEW r on i.REST_ID = r.REST_ID
# WHERE ADDRESS LIKE "%서울%"
# GROUP BY REST_ID
# ORDER BY SCORE DESC, FAVORITES DESC

SELECT a.REST_ID 
     , a.REST_NAME
     , a.FOOD_TYPE
     , a.FAVORITES
     , a.ADDRESS
     , ROUND(AVG(b.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS a JOIN REST_REVIEW AS b ON a.REST_ID = b.REST_ID
WHERE a.ADDRESS like '서울%'
GROUP BY REST_ID
ORDER BY SCORE DESC