select I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I, 
    (SELECT T.ITEM_ID 
     FROM ITEM_TREE T,
        (SELECT ITEM_ID FROM ITEM_INFO
         WHERE RARITY = "RARE"
        ) AS I1
     WHERE I1.ITEM_ID = T.PARENT_ITEM_ID) AS I2
WHERE I.ITEM_ID = I2.ITEM_ID
ORDER BY ITEM_ID DESC;