SELECT MONTH(START_DATE) as MONTH, t1.CAR_ID, COUNT(*) AS RECORDS
FROM(
    SELECT CAR_ID, COUNT(*) AS RECORD
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN "2022-08-01" AND "2022-10-31"
    GROUP BY CAR_ID
    HAVING RECORD >= 5
) as t1
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY t2 ON t1.CAR_ID = t2.CAR_ID
WHERE START_DATE BETWEEN "2022-08-01" AND "2022-10-31"
GROUP BY t1.CAR_ID, MONTH(START_DATE)
ORDER BY MONTH(START_DATE), t1.CAR_ID DESC