SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS AS D JOIN SKILLCODES AS S ON D.SKILL_CODE & S.CODE = S.CODE
WHERE NAME = "C#" OR NAME = "Python"
GROUP BY ID, EMAIL, FIRST_NAME, LAST_NAME
ORDER BY ID;